/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapplication;

import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.blue;
import static java.awt.Color.gray;
import static java.awt.Color.red;
import static java.awt.Color.white;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static myapplication.studentResult.exit;

/**
 *
 * @author Vs
 */
public class addstudent extends javax.swing.JFrame {
 Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;

    public addstudent() {
        initComponents();
    
        this.setLocationRelativeTo(null);
        updateCombo();    // this is the constructor for combobox 
        
    }
    
    
    public void updateCombo(){   // its for combox to fatch number of data data from the database 
    try{
   conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/adminlogin","root","root");
   String sql = " Select * from studentdetails ";
   pst = conn.prepareStatement(sql);
   rs = pst.executeQuery();
   while(rs.next())
   {
   String name = rs.getString("rollno");
   combobox.addItem(name);
   }
    }
    catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        rollno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        stdname = new javax.swing.JTextField();
        fathername = new javax.swing.JTextField();
        phoneno = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pincode = new javax.swing.JTextField();
        attachimage = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lable4image = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonReser = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        show_validation_here = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(870, 575));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 550, -1));

        rollno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rollno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollnoActionPerformed(evt);
            }
        });
        rollno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rollnoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rollnoKeyTyped(evt);
            }
        });
        jPanel2.add(rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 30, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText(" Roll No       :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 30, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Father's name  : ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 180, 152, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Student name   :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 78, 160, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Phone No           :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 313, 158, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Address              :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 376, 172, 30));

        stdname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stdname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stdnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stdnameKeyTyped(evt);
            }
        });
        jPanel2.add(stdname, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 78, 171, 30));

        fathername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(fathername, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 181, 250, -1));

        phoneno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonenoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phonenoKeyTyped(evt);
            }
        });
        jPanel2.add(phoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 313, 250, -1));

        address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressKeyTyped(evt);
            }
        });
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 363, 250, 56));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Pin-code            :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 231, 158, -1));

        pincode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pincode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pincodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pincodeKeyTyped(evt);
            }
        });
        jPanel2.add(pincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 228, 250, -1));

        attachimage.setBackground(new java.awt.Color(204, 204, 255));
        attachimage.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        attachimage.setText("Upload photo");
        attachimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachimageActionPerformed(evt);
            }
        });
        jPanel2.add(attachimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 110, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Gender               :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 267, 166, 30));

        gender.setEditable(true);
        gender.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "     Select", "Male", "Female" }));
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 269, 100, 29));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(150, 141));
        jDesktopPane1.setLayout(new java.awt.CardLayout());

        lable4image.setForeground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.add(lable4image, "card2");

        jPanel2.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 140));
        jPanel2.add(path, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 270, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 570, 450));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 170, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("ADD MARKS");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 170, 60));

        jButtonReser.setBackground(new java.awt.Color(255, 255, 255));
        jButtonReser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonReser.setText("RESET");
        jButtonReser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jButtonReser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonReserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonReserMouseExited(evt);
            }
        });
        jButtonReser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReserActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReser, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 170, 40));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Update");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 170, 40));

        show_validation_here.setForeground(java.awt.Color.red);
        getContentPane().add(show_validation_here, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 479, 101, 10));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        jLabel2.setText(" Students Detail");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 380, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setText("X");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setText("-");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, 50));

        combobox.setBackground(new java.awt.Color(204, 204, 255));
        combobox.setEditable(true);
        combobox.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  Select Roll_No" }));
        combobox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboboxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });
        getContentPane().add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 220, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 240, 10));

        username.setBackground(new java.awt.Color(153, 153, 153));
        username.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        username.setBorder(null);
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usernameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usernameMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                usernameMouseReleased(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 180, 20));

        password.setBackground(new java.awt.Color(153, 153, 153));
        password.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        password.setBorder(null);
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                passwordMouseReleased(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 180, 20));

        jLabel14.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 40));

        jLabel15.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("User name");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 240, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 260, 170));

        jLabel13.setFont(new java.awt.Font("Shruti", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Student Username and Password");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
       
    
    private void jButtonReserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReserActionPerformed
       rollno.setText(null);
  
       stdname.setText(null);
       fathername.setText(null);
        
       phoneno.setText(null);
       address.setText(null);
       pincode.setText(null);
       username.setText(null);
       password.setText(null);
       gender.setSelectedItem(null);
       lable4image.setText(null);
     
    }//GEN-LAST:event_jButtonReserActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        marks info = new marks();
        info.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rollnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollnoKeyTyped
  char c=evt.getKeyChar();  
     
   if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) ||c==KeyEvent.VK_DELETE))
         {getToolkit().beep();
           evt.consume();
         }         
    }//GEN-LAST:event_rollnoKeyTyped

    private void phonenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenoKeyTyped
  char c=evt.getKeyChar();  
     
   if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) ||c==KeyEvent.VK_DELETE))
         {getToolkit().beep();
           evt.consume();
         }         // TODO add your handling code here:
    }//GEN-LAST:event_phonenoKeyTyped

    private void pincodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pincodeKeyTyped
         char c=evt.getKeyChar();  
     
   if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) ||c==KeyEvent.VK_DELETE))
         {getToolkit().beep();
           evt.consume();
         } 
    }//GEN-LAST:event_pincodeKeyTyped

    private void stdnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stdnameKeyPressed
         
    
    }//GEN-LAST:event_stdnameKeyPressed

    private void stdnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stdnameKeyTyped
        
    }//GEN-LAST:event_stdnameKeyTyped

    private void rollnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollnoKeyPressed
       
         int key = evt.getKeyCode();
         
         if(key>=evt.VK_0&&key<=evt.VK_4||(key>=evt.VK_NUMPAD0&&key<=evt.VK_NUMPAD4)||key==KeyEvent.VK_BACK_SPACE)
         {
         rollno.setEditable(true);
         rollno.setBackground(Color.gray);
         }
         else{
             rollno.setEditable(false);
         rollno.setBackground(Color.white);
         }
       
    }//GEN-LAST:event_rollnoKeyPressed

    private void phonenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenoKeyPressed
    
        int key = evt.getKeyCode();
         
         if(key>=evt.VK_0&&key<=evt.VK_9||(key>=evt.VK_NUMPAD0&&key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACK_SPACE)
         {
         phoneno.setEditable(true);
        phoneno.setBackground(Color.gray);
         }
         else{
            phoneno.setEditable(false);
        phoneno.setBackground(Color.white);
         }
         
        try{
         int i=Integer.parseInt(rollno.getText());
         show_validation_here.setText("");
     }
     catch(NumberFormatException e){
        
         show_validation_here.setText("invalid number");
     }         
    }//GEN-LAST:event_phonenoKeyPressed

    private void pincodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pincodeKeyPressed
      
        
    }//GEN-LAST:event_pincodeKeyPressed

    private void rollnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollnoActionPerformed
    
    }//GEN-LAST:event_rollnoActionPerformed

    private void addressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyTyped
         
    }//GEN-LAST:event_addressKeyTyped

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed

        if(combobox.getSelectedItem().toString().equals("  Select Roll_No"))
        {
          rollno.setText(null);
  
       stdname.setText(null);
       fathername.setText(null);
        
       phoneno.setText(null);
       address.setText(null);
       pincode.setText(null);
       username.setText(null);
       password.setText(null);
       gender.setSelectedItem(null);
       lable4image.setText(null);  
       
        }
         
        
    }//GEN-LAST:event_comboboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
 Class.forName("com.mysql.jdbc.Driver");
 Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/adminlogin","root","root"); // database name
 String sql= "insert into studentdetails values (?,?,?,?,?,?,?,?,?,?)"; // table name
 PreparedStatement pstmt = conn.prepareStatement(sql);
 
 pstmt.setInt(1,Integer.parseInt(rollno.getText()));  // when we use integer type them it,is wrong use INTEGERPARSE  to use that type of problem 
 
 pstmt.setString(2,stdname.getText());
 
 pstmt.setString(3,fathername.getText());
 
 pstmt.setInt(4,Integer.parseInt(pincode.getText()));

 String gnd;   // this is use for combpBOX  to save data into the database 
 gnd= gender.getSelectedItem().toString();
 pstmt.setString(5,gnd);
 
 
 pstmt.setInt(6,Integer.parseInt(phoneno.getText()));
 
 pstmt.setString(7,address.getText());
 
 pstmt.setBytes(8,photo);
  
 pstmt.setString(9,username.getText());
 
 pstmt.setString(10,password.getText());
 
 
 pstmt.executeUpdate();
 JOptionPane.showMessageDialog(null," insertion successfull");
 conn.close();
 
 }
 catch(Exception e){
 JOptionPane.showMessageDialog(null,e);
 }
 updateCombo(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseEntered
  username.setForeground(white);
    }//GEN-LAST:event_usernameMouseEntered

    private void usernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseExited
      username.setForeground(black);
    }//GEN-LAST:event_usernameMouseExited

    private void usernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMousePressed
      username.setForeground(red);
    }//GEN-LAST:event_usernameMousePressed

    private void usernameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseReleased
    username.setForeground(white);    // TODO add your handling code here:
    }//GEN-LAST:event_usernameMouseReleased

    private void passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseEntered
password.setForeground(white);
    }//GEN-LAST:event_passwordMouseEntered

    private void passwordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseExited
        password.setForeground(black);   // TODO add your handling code here:
    }//GEN-LAST:event_passwordMouseExited

    private void passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMousePressed
        password.setForeground(red);
    }//GEN-LAST:event_passwordMousePressed

    private void passwordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseReleased
        password.setForeground(white);
    }//GEN-LAST:event_passwordMouseReleased

    private void attachimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachimageActionPerformed
   JFileChooser chooser= new JFileChooser();
   chooser.showOpenDialog(null);
   File f = chooser.getSelectedFile();
  lable4image.setIcon(new ImageIcon(f.toString()));
  filename = f.getAbsolutePath();
  path.setText(filename);
  
  try{
  File image = new File(filename);
  FileInputStream fis = new FileInputStream(image);
  ByteArrayOutputStream bos = new ByteArrayOutputStream();
  byte[] buf = new byte[1024];
   for(int readNum; (readNum=fis.read(buf))!=-1;)
   {
       bos.write(buf,0,readNum);
       
   }
   photo=bos.toByteArray();
  }
  catch(Exception e){
  JOptionPane.showMessageDialog(null,e);
  }
    }//GEN-LAST:event_attachimageActionPerformed

    private void comboboxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboboxPopupMenuWillBecomeInvisible
      String temp = (String)combobox.getSelectedItem();
      String sql="Select * from   `adminlogin`.`studentdetails` where rollno=? ";  //in the combobox we are showing the rollno of every student
        try{
            byte[] imageBytes;
            Image image;
      pst = conn.prepareStatement(sql);     
      pst.setString(1,temp);      
      rs=pst.executeQuery();
    
      while(rs.next())
      {
          String add0 = rs.getString("rollno");
          rollno.setText(add0);
          
          String add1 = rs.getString("stdname");
          stdname.setText(add1);
          
          String add2 = rs.getString("fathername");
          fathername.setText(add2);
          
          String add3 = rs.getString("pincode");
         pincode.setText(add3);
          
        
          
          String add5 = rs.getString("phoneno");
          phoneno.setText(add5);
          
          String add6 = rs.getString("address");
         address.setText(add6);
         
         String add7 = rs.getString("photo");
         lable4image.setText(add7);
          
         String add8 = rs.getString("username");
         username.setText(add8);
         
         String add9 = rs.getString("pssword");
         password.setText(add9);
         
         String add10 = rs.getString("gender");
         gender.setSelectedItem(add10);
      
       String add11 = rs.getString("photo");
       imageBytes = rs.getBytes(8);
       image=getToolkit().createImage(imageBytes);
       ImageIcon icon= new ImageIcon(image);
         lable4image.setIcon(icon);
    
      }
      }
      catch(Exception e){}
    }//GEN-LAST:event_comboboxPopupMenuWillBecomeInvisible

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
  userdetail st= new userdetail();
        st.setVisible(true);                //2   
            dispose(); 
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
      jLabel3.setForeground(red);    
      jLabel2.setForeground(gray); 
     jLabel13.setForeground(black);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
      jLabel4.setForeground(blue); 
      jLabel2.setForeground(gray);
      jLabel13.setForeground(black);   
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
     jLabel3.setForeground(black);    
      jLabel2.setForeground(black); 
     jLabel13.setForeground(gray);       
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
      jLabel4.setForeground(black);      
        jLabel2.setForeground(black); 
     jLabel13.setForeground(gray); 
    }//GEN-LAST:event_jLabel4MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
   jButton2.setBackground(gray);
   jButton2.setForeground(white);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
jButton2.setBackground(white); 
jButton2.setForeground(black);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
 jButton1.setBackground(gray);
   jButton1.setForeground(white);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
 jButton1.setBackground(white);
   jButton1.setForeground(black);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jButtonReserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReserMouseEntered
 jButtonReser.setBackground(gray);
   jButtonReser.setForeground(white);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReserMouseEntered

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        userdetail Info = new userdetail();
        Info.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonReserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReserMouseExited
 jButtonReser.setBackground(white);
   jButtonReser.setForeground(black);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReserMouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
 jButton4.setBackground(gray);
   jButton4.setForeground(white);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
 jButton4.setBackground(white);
   jButton4.setForeground(black);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton attachimage;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JTextField fathername;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonReser;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lable4image;
    private javax.swing.JTextField password;
    private javax.swing.JTextField path;
    private javax.swing.JTextField phoneno;
    private javax.swing.JTextField pincode;
    private javax.swing.JTextField rollno;
    private javax.swing.JLabel show_validation_here;
    private javax.swing.JTextField stdname;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
byte[] photo=null;
String filename=null;

    private void While(boolean next) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
