/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapplication;
import java.sql.*;
import javax.swing.*;
import java.awt.event.WindowEvent;

import static myapplication.userdetail.name1;
import static myapplication.userdetail.name2;


         

/**
 *
 * @author manas singh
 */

public class loginSsystem extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;


    /**
     * Creates new form loginSsystem
     */
    public loginSsystem() {
        
        initComponents();
        this.setLocationRelativeTo(null);
  //make the frame to center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        checkbox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabelcross = new javax.swing.JLabel();
        jLabelmini = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 204));
        setFont(new java.awt.Font("Adobe Arabic", 1, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(531, 342));
        setMinimumSize(new java.awt.Dimension(531, 342));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(531, 342));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(334, 340));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("User-Name  :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 110, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Password    :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 110, 40));

        username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 280, 40));

        password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 280, 40));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Sign-In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 140, 50));

        checkbox.setBackground(new java.awt.Color(204, 204, 255));
        checkbox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        checkbox.setText("show password");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 510, 260));

        jLabel5.setBackground(new java.awt.Color(255, 153, 102));
        jLabel5.setFont(new java.awt.Font("Serif", 1, 46)); // NOI18N
        jLabel5.setText(" LogIn");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 60));

        jLabelcross.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelcross.setText("x");
        jLabelcross.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelcross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcrossMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelcross, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, -10, -1, 60));

        jLabelmini.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelmini.setText("-");
        jLabelmini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabelmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 20, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("help ?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 50, -1));

        jComboBox1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "subject1", "subject2", "subject3", "subject4", "subject5", "subject6" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        /*
                           to login by clicking enter button , 
        go to password section right/click and choose key pressed and past whole code in this "if STATEMENT"
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           CPOY THE WHOLE CODE, WHICH WILL BE APPLIED ON BUTTON       
        }        
        */
      try{  
        conn = MySqlConnection.ConnectDB();
        
        String Sql="Select * from `adminlogin`.`login` where username='"+username.getText()+"' and password='"+password.getText()+"' and subject='"+jComboBox1.getSelectedItem()+"'  ";
        //here select from table waale me table ka maan lekhte hai
        //database ek he hoota hai bs usme "`adminlogin`.`login`" ye waala sb ka alag hooota hai so that
        //ek databse ke ander he kethne saare "select * from <tablename>" add ho sake
        
        try{ // first try catch block     // leacture value get and set into the 
            
            userdetail usr = new userdetail();
            userdetail.leacture.setText(loginSsystem.jComboBox1.getSelectedItem().toString());
            /* usr.setVisible(true); */   
             // comment beacuse in below code do the same afetr varifying the data from the database 
             // if it present into the system ... open the nxt frame without varifying the username and password 3
             
        }  
        catch(Exception e){}
        
        try{
          
        
        Statement st = conn.createStatement();
        
        ResultSet rs = st.executeQuery(Sql);
        
        if(rs.next())
        {
        new userdetail().setVisible(true);
        dispose();
        
        name1.setText(rs.getString(1));
         userdetail.leacture.setText(loginSsystem.jComboBox1.getSelectedItem().toString());
        
        name2.setText(rs.getString(1));
        
        }
        else
        {
        JOptionPane.showMessageDialog(null,"check your input data","access denied",JOptionPane.ERROR_MESSAGE);
        }
        }
        
        catch(SQLException e){
        
        JOptionPane.showMessageDialog(null,e);
        
        } 
        
        
      }
      catch(Exception e){
      JOptionPane.showMessageDialog(null,e);
      } 
       
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        /*    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
        conn = MySqlConnection.ConnectDB();
        
        String Sql="Select * from `adminlogin`.`login` where username='"+username.getText()+"' and password='"+password.getText()+"'";
        //here select from table waale me table ka maan lekhte hai
        //database ek he hoota hai bs usme "`adminlogin`.`login`" ye waala sb ka alag hooota hai so that
        //ek databse ke ander he kethne saare "select * from <tablename>" add ho sake
        try{
        
        Statement st = conn.createStatement();
        
        ResultSet rs = st.executeQuery(Sql);
        
        if(rs.next())
        {
        new userdetail().setVisible(true);
        dispose();
        
        name1.setText(rs.getString(1));
        name2.setText(rs.getString(1));
        }
        else
        {
        JOptionPane.showMessageDialog(null,"Invalid user-name or password","access denied",JOptionPane.ERROR_MESSAGE);
        }
        }
        
        catch(SQLException e){
        
        JOptionPane.showMessageDialog(null,e);
        
        }
        }*/
    }//GEN-LAST:event_passwordKeyPressed

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
   if(checkbox.isSelected())
   {
   password.setEchoChar((char)0);
   }
   else {
   password.setEchoChar('*');
   }
    }//GEN-LAST:event_checkboxActionPerformed

    private void jLabelcrossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcrossMouseClicked
dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabelcrossMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

    }//GEN-LAST:event_formMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginSsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginSsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginSsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginSsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginSsystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JButton jButton1;
    public static final javax.swing.JComboBox<String> jComboBox1 = new javax.swing.JComboBox<>();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelcross;
    private javax.swing.JLabel jLabelmini;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPasswordField password;
    public static javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
     
     
    
    private void systemExit()
    {
        WindowEvent winCloseing =new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    }

    static class setVisible {

        public setVisible(boolean b) {
        }
    }

}

