/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapplication;

import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.blue;
import static java.awt.Color.gray;
import static java.awt.Color.red;
import static java.awt.Color.white;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

import java.awt.event.KeyEvent;
import static java.lang.ProcessBuilder.Redirect.to;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.value;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeJava.to;

/**
 *
 * @author Vs
 */
public class marks extends javax.swing.JFrame {
 Connection conn=null;                             //these are local variable thus local variable are decleared there and global variables are decleared abouve i.e. import waale section me 
PreparedStatement pst=null;
ResultSet rs=null;


    /**
     * Creates new form marks
     */
    public marks() {
        initComponents();
        
        this.setLocationRelativeTo(null);
           updateCombo();    // this is the constructor for combobox 
           Update_tables1();
           Update_tables();    // this is the constructor for update the table or simply to say that that it is calling of a function  
           
    }
    
        private void Update_tables1(){
     try {
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/adminlogin","root","root");
         String sql = "Select rollno , stdname from studentdetails";       // Select rollno , "stdname" from studentdetails  if we use these invented comosc then values inside these comoas are shown 
            pst = conn.prepareStatement(sql);
             rs = pst.executeQuery();
             jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    
     }
     catch (SQLException e) {
        JOptionPane.showMessageDialog(null,e);
     } 
 }
    
    
    
 private void Update_tables(){    // thsi constructor is use  to  show the database values into the jtable but number of parameters are equal on both sides
     try {
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/adminlogin","root","root");
         String sql = "Select * from studentmarks";
            pst = conn.prepareStatement(sql);
             rs = pst.executeQuery();
             
             jTabledatatable.setModel(DbUtils.resultSetToTableModel(rs));
             
         
     }
     catch (SQLException e) {
        JOptionPane.showMessageDialog(null,e);
     } 
 }
public void updateCombo(){   // its for combox to fatch number of data data from the database 
  
    try{
   conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/adminlogin","root","root");
   String sql = " Select * from studentdetails ";
   pst = conn.prepareStatement(sql);
   rs = pst.executeQuery();
   while(rs.next())
   {
   String name = rs.getString("rollno");
   ComboBox2.addItem(name);
      
   }
    }
    catch(Exception e){}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sub1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sub2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sub3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sub4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sub5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sub6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sub7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        totalMraks = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        totalMarksGetByStudents = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        win = new javax.swing.JTextField();
        ComboBox1 = new javax.swing.JComboBox<>();
        ComboBox2 = new javax.swing.JComboBox<>();
        sub1Total = new javax.swing.JTextField();
        sub2Total = new javax.swing.JTextField();
        sub3Total = new javax.swing.JTextField();
        sub4Total = new javax.swing.JTextField();
        sub5Total = new javax.swing.JTextField();
        sub6Total = new javax.swing.JTextField();
        sub7Total = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabledatatable = new javax.swing.JTable();
        reset = new javax.swing.JButton();
        gnrtRESULT = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        rank = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jTextFieldexam = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextFieldroll_no = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TextFieldsearch = new javax.swing.JTextField();
        textsno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1433, 621));
        setMinimumSize(new java.awt.Dimension(1433, 621));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1433, 621));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Subject 1    :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 113, 28));

        sub1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub1KeyTyped(evt);
            }
        });
        jPanel2.add(sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 115, 62, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Subject2     :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 146, 113, 28));

        sub2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub2KeyTyped(evt);
            }
        });
        jPanel2.add(sub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 149, 62, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Subject3     :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 113, 28));

        sub3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub3KeyTyped(evt);
            }
        });
        jPanel2.add(sub3, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 183, 62, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Subject4     :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 214, -1, 28));

        sub4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub4KeyTyped(evt);
            }
        });
        jPanel2.add(sub4, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 217, 62, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Subject5     :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 248, -1, 28));

        sub5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub5KeyTyped(evt);
            }
        });
        jPanel2.add(sub5, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 251, 62, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Subject6     :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 282, -1, 28));

        sub6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub6KeyTyped(evt);
            }
        });
        jPanel2.add(sub6, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 285, 62, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Subject7     :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 28));

        sub7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub7KeyTyped(evt);
            }
        });
        jPanel2.add(sub7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 62, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Total Marks :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 28));

        totalMraks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalMraks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalMraksKeyTyped(evt);
            }
        });
        jPanel2.add(totalMraks, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 63, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("ROLL_NO    :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, -1, 30));

        totalMarksGetByStudents.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalMarksGetByStudents.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalMarksGetByStudentsKeyTyped(evt);
            }
        });
        jPanel2.add(totalMarksGetByStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 60, 29));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("/");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 114, -1, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("/");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 148, -1, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("/");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 182, -1, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("/");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 216, -1, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("/");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 250, -1, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("/");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 284, -1, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("/");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 10, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("/");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("AVERAGE    :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 124, 28));

        win.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        win.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                winKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                winKeyTyped(evt);
            }
        });
        jPanel2.add(win, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 145, -1));

        ComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Select Exam", "   MST 1", "   MST 2", "   MST 3", " " }));
        ComboBox1.setToolTipText("");
        ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(ComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 135, 50));

        ComboBox2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Select", " " }));
        jPanel2.add(ComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 74, 142, 30));

        sub1Total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sub1Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub1TotalKeyTyped(evt);
            }
        });
        jPanel2.add(sub1Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 112, 60, 29));

        sub2Total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sub2Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub2TotalKeyTyped(evt);
            }
        });
        jPanel2.add(sub2Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 146, 60, 29));

        sub3Total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sub3Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub3TotalKeyTyped(evt);
            }
        });
        jPanel2.add(sub3Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 180, 60, 29));

        sub4Total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sub4Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub4TotalKeyTyped(evt);
            }
        });
        jPanel2.add(sub4Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 214, 60, 29));

        sub5Total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sub5Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub5TotalKeyTyped(evt);
            }
        });
        jPanel2.add(sub5Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 248, 60, 29));

        sub6Total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sub6Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub6TotalKeyTyped(evt);
            }
        });
        jPanel2.add(sub6Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 282, 60, 29));

        sub7Total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sub7Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sub7TotalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub7TotalKeyTyped(evt);
            }
        });
        jPanel2.add(sub7Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 60, 29));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 290, 460));

        jTabledatatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No", "Exams", "Roll_No", "OutOFF", "sub1", "sub2", "sub3", "sub4", "sub5", "sub6", "sub7", "Totala marks", "OUT-TM", "Aveage", "Rank"
            }
        ));
        jTabledatatable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabledatatableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabledatatable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 920, 370));

        reset.setBackground(new java.awt.Color(255, 255, 255));
        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setText("Reset");
        reset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 190, 40));

        gnrtRESULT.setBackground(new java.awt.Color(255, 255, 255));
        gnrtRESULT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gnrtRESULT.setText("Add Result");
        gnrtRESULT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        gnrtRESULT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gnrtRESULT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gnrtRESULTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gnrtRESULTMouseExited(evt);
            }
        });
        gnrtRESULT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnrtRESULTActionPerformed(evt);
            }
        });
        getContentPane().add(gnrtRESULT, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 190, 40));

        jSeparator1.setBackground(new java.awt.Color(255, 204, 153));
        jSeparator1.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 490, 10));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("RANK          :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 130, 28));

        rank.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rank.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rankKeyTyped(evt);
            }
        });
        getContentPane().add(rank, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, 200, -1));

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setText("Delete Selection");
        delete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 200, 40));

        jTextFieldexam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldexam.setText("    ");
        jTextFieldexam.setBorder(null);
        jTextFieldexam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jTextFieldexam, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 50, 10));

        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 40, 10));

        jTextFieldroll_no.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextFieldroll_no.setBorder(null);
        jTextFieldroll_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldroll_noKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldroll_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 40, 10));

        jTextField2.setBorder(null);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 50, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel3.setText("Marks Record");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 70));

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setText("Update");
        update.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 490, 200, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll_No", "Name"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 50, 180, 560));

        TextFieldsearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextFieldsearch.setForeground(new java.awt.Color(153, 153, 153));
        TextFieldsearch.setText("Search Roll-NO Here...");
        TextFieldsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldsearchMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextFieldsearchMouseExited(evt);
            }
        });
        TextFieldsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldsearchKeyReleased(evt);
            }
        });
        getContentPane().add(TextFieldsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 230, -1));

        textsno.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        textsno.setForeground(new java.awt.Color(102, 102, 102));
        textsno.setText("S.No...");
        textsno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textsnoMouseClicked(evt);
            }
        });
        getContentPane().add(textsno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 90, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel13.setText("X");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 0, -1, 40));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel25.setText("-");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       textsno.setText(null);
       
        sub1.setText(null);
       sub2.setText(null);
       sub3.setText(null);
       sub4.setText(null);
       sub5.setText(null);
       sub6.setText(null);
       sub7.setText(null);
      
       totalMraks.setText(null);
       rank.setText(null);
       win.setText(null);
       sub1Total.setText(null);
       sub2Total.setText(null);
       sub3Total.setText(null);
       sub4Total.setText(null);
       sub5Total.setText(null);
       sub6Total.setText(null);
       sub7Total.setText(null);
       
       totalMarksGetByStudents.setText(null);
       reset.setText(null);
       jTextFieldroll_no.setText(null);
       jTextFieldexam.setText(null);
       
          
    }//GEN-LAST:event_resetActionPerformed

    private void gnrtRESULTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnrtRESULTActionPerformed
  
        // here we use multiple try{} catch(){}
        
        /*
        syntax of multiple 
        try{
        
        try{
        statement
        }
        catch(Execptione){}
        
        try{
        statement 
        }
        catch(Execption e){}
        
        }
        catch(execption e){}
        */
 try{  // the  main try..catch  block
     
     //this below code is for add the data into the table 
     
   try{     // first try...catch  block
        // marks get by students 
        
        int a= Integer.parseInt( sub1.getText());
       int b= Integer.parseInt( sub2.getText());
       int c= Integer.parseInt( sub3.getText());
       int d= Integer.parseInt( sub4.getText());
       int e= Integer.parseInt( sub5.getText());
       int f= Integer.parseInt(  sub6.getText());
       int g= Integer.parseInt( sub7.getText()); 
       
      
       // from there total marks waala section hai
       
         int i= Integer.parseInt( sub1Total.getText());
         int j= Integer.parseInt( sub2Total.getText());
         int k= Integer.parseInt( sub3Total.getText());
         int l= Integer.parseInt( sub4Total.getText());
         int m= Integer.parseInt( sub5Total.getText());
         int n= Integer.parseInt( sub6Total.getText());
         int o= Integer.parseInt( sub7Total.getText());
         
        
          // total marks kethne me se studenst to kethne mile 
          int x=i+j+k+l+m+n+o;
          totalMarksGetByStudents.setText(x+"");
       
                  // below wala total maks get by student                   
       int z=a+b+c+d+e+f+g;                      /* z=totalMarksGetByStudents , x= totalmarks ( kethne me se marks aaye ), y=jTextFieldAVERAGE (for average)   */
       totalMraks.setText(z+"");
          
       // below wala average ka hai 
       int y=(a+b+c+d+e+f+g)*100/x;
       win.setText(y+" % ");
      
       
     // rank section hai ye below waala
     
       if((z>=330) && (z==350))
           
       rank.setText("1st rank");
      
       else if((z>=297) && (z<=330))
       rank.setText("2nd rank");
      
       else if((z>=263) && (z<=297) )
       rank.setText("3rd rank");    
       
       else if((z>=230) && (z<=263))
       rank.setText("4th rank");      
       
       else if((z>=195) && (z<=230))
       rank.setText("5th rank");     
       
       else if((z>=178) && (z<=195))
       rank.setText("6th rank");      
       
       else if((z>=123) && (z<=178))
       rank.setText("7th rank");      
       
       else 
       
       rank.setText("check your marks ");
       
           
      
      DefaultTableModel model = (DefaultTableModel)jTabledatatable.getModel();
jTextField2.setText(ComboBox2.getSelectedItem().toString());       // this a way through which we can get comobox values into the text field and then this textfield values into the jtable
      jTextFieldexam.setText(ComboBox1.getSelectedItem().toString());
      model.addRow(new Object[]{textsno.getText(),jTextFieldexam.getText(),jTextField2.getText(),sub1Total.getText(),sub1.getText(),sub2.getText(),sub3.getText(),sub4.getText(),sub5.getText(),sub6.getText(),sub7.getText(),totalMraks.getText(),totalMarksGetByStudents.getText(),win.getText(),rank.getText()});     
    }
     catch(Exception e){}  
 
    // below code is for save the data into the database 
   
     try{    // second try..catch block
   
         
      
 Class.forName("com.mysql.jdbc.Driver");
 Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/adminlogin","root","root"); // database name
 String sql= "insert into studentmarks values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"; // table name
 PreparedStatement pstmt = conn.prepareStatement(sql);
 
 
 pstmt.setString(1,textsno.getText());
 
 String gnd;   // this is use for combpBOX  to save data into the database 
 gnd= ComboBox1.getSelectedItem().toString();
 pstmt.setString(2,gnd);
 
  String gnd2;   // this is use for combpBOX  to save data into the database 
 gnd2 = ComboBox2.getSelectedItem().toString();
 pstmt.setString(3,gnd2);
 
 pstmt.setString(4,sub1Total.getText());
 
 pstmt.setString(5,sub1.getText());
 
 pstmt.setString(6,sub2.getText());
 
 pstmt.setString(7,sub3.getText());
 pstmt.setString(8,sub4.getText());
 pstmt.setString(9,sub5.getText());
 pstmt.setString(10,sub6.getText());
 pstmt.setString(11,sub7.getText());
 
 pstmt.setString(12,totalMraks.getText());
 
 pstmt.setString(13,totalMarksGetByStudents.getText());
 
pstmt.setString(14,win.getText()); 

 pstmt.setString(15,rank.getText());
 
 
 pstmt.executeUpdate();
 JOptionPane.showMessageDialog(null," insertion successfull");
 conn.close();
        
 }

 catch(Exception e){} 
 }
 catch(Exception e){}
       
    }//GEN-LAST:event_gnrtRESULTActionPerformed

    private void rankKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rankKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_rankKeyTyped

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTabledatatable.getModel();
       
       try
       {
          int SelectedRowIndex =jTabledatatable.getSelectedRow();
          model.removeRow(SelectedRowIndex);
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_deleteActionPerformed

    private void winKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_winKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_winKeyTyped

    private void totalMarksGetByStudentsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalMarksGetByStudentsKeyTyped
        char c=evt.getKeyChar();

        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) ||c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_totalMarksGetByStudentsKeyTyped

    private void totalMraksKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalMraksKeyTyped
        char c=evt.getKeyChar();

        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) ||c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_totalMraksKeyTyped

    private void sub7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub7KeyTyped
        char c=evt.getKeyChar();

        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) ||c==KeyEvent.VK_DELETE))
        {getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_sub7KeyTyped

    private void sub6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub6KeyTyped
        char c=evt.getKeyChar();

        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) ||c==KeyEvent.VK_DELETE))
        {getToolkit().beep();
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_sub6KeyTyped

    private void sub5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub5KeyTyped
        char c=evt.getKeyChar();

        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) ||c==KeyEvent.VK_DELETE))
        {getToolkit().beep();
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_sub5KeyTyped

    private void sub4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub4KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) ||c==KeyEvent.VK_DELETE))
        {getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_sub4KeyTyped

    private void sub3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub3KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) ||c==KeyEvent.VK_DELETE))
        {getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_sub3KeyTyped

    private void sub2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub2KeyTyped
        // TODO add your handling code here:
        char e=evt.getKeyChar();

        if(!(Character.isDigit(e) || (e==KeyEvent.VK_BACK_SPACE) ||e==KeyEvent.VK_DELETE))
        {getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_sub2KeyTyped

    private void sub1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub1KeyTyped
        char c=evt.getKeyChar();

        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) ||c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_sub1KeyTyped

    private void ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox1ActionPerformed

    private void jTextFieldroll_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldroll_noKeyTyped
        char c=evt.getKeyChar();

        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) ||c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();   // may be beep
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldroll_noKeyTyped

    private void sub1TotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub1TotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1TotalKeyTyped

    private void sub2TotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub2TotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sub2TotalKeyTyped

    private void sub3TotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub3TotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sub3TotalKeyTyped

    private void sub4TotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub4TotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sub4TotalKeyTyped

    private void sub5TotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub5TotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sub5TotalKeyTyped

    private void sub6TotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub6TotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sub6TotalKeyTyped

    private void sub7TotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub7TotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sub7TotalKeyTyped

    private void winKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_winKeyPressed
        
    }//GEN-LAST:event_winKeyPressed

    private void sub7TotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub7TotalKeyPressed
    
   
              // TODO add your handling code here:
    }//GEN-LAST:event_sub7TotalKeyPressed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
 try{
    String value1 = ComboBox1.getSelectedItem().toString();
    String value2 = ComboBox2.getSelectedItem().toString();
    String value3 = sub1Total.getText();
    String value4 = sub1.getText();
    String value5 = sub2.getText();
    String value6 = sub3.getText();
    String value7 = sub4.getText();
    String value8 = sub5.getText();
    String value9 = sub6.getText();
    String value10 = sub7.getText();
    String value11 = totalMraks.getText();    
    String value12 = totalMarksGetByStudents.getText();
    String value13 = win.getText();
    String value14 = rank.getText();
    
    
    String sql = "update studentmarks set exam='"+value1+"' , rollno='"+value2+"' ,outoff='"+value3+"',sub1='"+value4+"' , sub2='"+value5+"' , sub3='"+value6+"', sub4='"+value7+"' , sub5='"+value8+"',sub6='"+value9+"',sub7='"+value10+"',totalmaks='"+value11+"',out-mt='"+value12+"',average='"+value13+"',rank='"+value14+"' where rollno='"+value2+"'  ";            
    pst=conn.prepareStatement(sql);
    pst.execute();
    
 }
 catch(Exception e){
     JOptionPane.showMessageDialog(null,e);
 }   
       
    }//GEN-LAST:event_updateActionPerformed

    private void jTabledatatableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabledatatableMouseClicked
     
    // this code is for to show table data into the textfield or into the combobox 
    
        int row = jTabledatatable.getSelectedRow();
      
       // combobox get means comcbonox se humne vo waale value le hai..... set measn hum se combobox me vo waale value set krvaaye hai 
      
       textsno.setText(jTabledatatable.getModel().getValueAt(row,0).toString());
       
       ComboBox1.setSelectedItem(jTabledatatable.getModel().getValueAt(row,1).toString());
      ComboBox2.setSelectedItem(jTabledatatable.getModel().getValueAt(row,2).toString());
      
      sub1Total.setText(jTabledatatable.getModel().getValueAt(row,3).toString());
      sub2Total.setText(jTabledatatable.getModel().getValueAt(row,3).toString());
      sub3Total.setText(jTabledatatable.getModel().getValueAt(row,3).toString());
      sub4Total.setText(jTabledatatable.getModel().getValueAt(row,3).toString());
      sub5Total.setText(jTabledatatable.getModel().getValueAt(row,3).toString());
      sub6Total.setText(jTabledatatable.getModel().getValueAt(row,3).toString());
      sub7Total.setText(jTabledatatable.getModel().getValueAt(row,3).toString());
      sub1.setText(jTabledatatable.getModel().getValueAt(row,4).toString());
      sub2.setText(jTabledatatable.getModel().getValueAt(row,5).toString());
      sub3.setText(jTabledatatable.getModel().getValueAt(row,6).toString());
      sub4.setText(jTabledatatable.getModel().getValueAt(row,7).toString());
      sub5.setText(jTabledatatable.getModel().getValueAt(row,8).toString());
      sub6.setText(jTabledatatable.getModel().getValueAt(row,9).toString());
      sub7.setText(jTabledatatable.getModel().getValueAt(row,10).toString());
      
      totalMraks.setText(jTabledatatable.getModel().getValueAt(row,11).toString());      
      totalMarksGetByStudents.setText( jTabledatatable.getModel().getValueAt(row,12).toString());
      win.setText( jTabledatatable.getModel().getValueAt(row,13).toString());
      rank.setText( jTabledatatable.getModel().getValueAt(row,14).toString());  // we have 14 values but these values are stating from 0-13 thatswhy 14 values is not elligable 
      
    }//GEN-LAST:event_jTabledatatableMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
/*
       try{
            
           String sql= " UPDATE `adminlogin`.`studentmarks` set exam=? , outoff=?,sub1=?,sub2=?,sub3=?,sub4=?,sub5=?,sub6=?,sub7=?,totalmaks=?,out-mt=?,average=?,rank=? where rollno=? ";
       pst = conn.prepareStatement(sql);
       
  pst.setString(0,ComboBox1.getSelectedItem().toString());
  pst.setString(1,ComboBox2.getSelectedItem().toString());
  pst.setString(2,sub1Total.getText());
  pst.setString(2,sub1Total.getText());
  pst.setString(2,sub2Total.getText());
  pst.setString(2,sub3Total.getText());
  pst.setString(2,sub4Total.getText());
  pst.setString(2,sub5Total.getText());
  pst.setString(2,sub6Total.getText());
  pst.setString(2,sub7Total.getText());
  
  pst.setString(3,sub1.getText());
  pst.setString(4,sub2.getText());
  pst.setString(5,sub3.getText());
  pst.setString(6,sub4.getText());
  pst.setString(7,sub5.getText());
  pst.setString(8,sub6.getText());
  pst.setString(9,sub7.getText());
  
  pst.setString(10,totalMraks.getText());
  pst.setString(11,totalMarksGetByStudents.getText());
  pst.setString(12,win.getText());
  pst.setString(13,rank.getText());
  
    
    pst.executeUpdate();
      updateJTable();
 JOptionPane.showMessageDialog(null," insertion successfull");
 conn.close();
       }
       catch(Exception e){}       
        */
    }//GEN-LAST:event_updateMouseClicked

    private void TextFieldsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldsearchKeyReleased

        /*  String qurey = jTextField4.getText().toLowerCase();

        filter(qurey);*/
        try{

            String query= "select * from studentmarks where rollno=?";
            PreparedStatement  pst = conn.prepareStatement(query);
            pst.setString(1,TextFieldsearch.getText());
            ResultSet rs = pst.executeQuery();
            jTabledatatable.setModel(DbUtils.resultSetToTableModel(rs));

            pst.close();

        }
        catch(Exception e){}

    }//GEN-LAST:event_TextFieldsearchKeyReleased

    private void TextFieldsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldsearchMouseClicked
      TextFieldsearch.setText("");
   
      TextFieldsearch.setForeground(black);      
    }//GEN-LAST:event_TextFieldsearchMouseClicked

    private void TextFieldsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldsearchMouseExited
        
    }//GEN-LAST:event_TextFieldsearchMouseExited

    private void textsnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textsnoMouseClicked
       textsno.setText("");
   
     textsno.setForeground(black);   
    }//GEN-LAST:event_textsnoMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        addstudent st= new addstudent();
        st.setVisible(true);             
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        jLabel3.setForeground(gray);
        jLabel13.setForeground(red);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        jLabel3.setForeground(black);
        jLabel13.setForeground(black);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        jLabel25.setForeground(blue);            // TODO add your handling code here:
        jLabel3.setForeground(gray);
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        jLabel25.setForeground(black);
        jLabel3.setForeground(black);
    }//GEN-LAST:event_jLabel25MouseExited

    private void gnrtRESULTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gnrtRESULTMouseEntered

    }//GEN-LAST:event_gnrtRESULTMouseEntered

    private void gnrtRESULTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gnrtRESULTMouseExited
     // TODO add your handling code here:
    }//GEN-LAST:event_gnrtRESULTMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new marks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox1;
    private javax.swing.JComboBox<String> ComboBox2;
    private javax.swing.JTextField TextFieldsearch;
    private javax.swing.JButton delete;
    private javax.swing.JButton gnrtRESULT;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTabledatatable;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldexam;
    private javax.swing.JTextField jTextFieldroll_no;
    private javax.swing.JTextField rank;
    private javax.swing.JButton reset;
    private javax.swing.JTextField sub1;
    private javax.swing.JTextField sub1Total;
    private javax.swing.JTextField sub2;
    private javax.swing.JTextField sub2Total;
    private javax.swing.JTextField sub3;
    private javax.swing.JTextField sub3Total;
    private javax.swing.JTextField sub4;
    private javax.swing.JTextField sub4Total;
    private javax.swing.JTextField sub5;
    private javax.swing.JTextField sub5Total;
    private javax.swing.JTextField sub6;
    private javax.swing.JTextField sub6Total;
    private javax.swing.JTextField sub7;
    private javax.swing.JTextField sub7Total;
    private javax.swing.JTextField textsno;
    private javax.swing.JTextField totalMarksGetByStudents;
    private javax.swing.JTextField totalMraks;
    private javax.swing.JButton update;
    private javax.swing.JTextField win;
    // End of variables declaration//GEN-END:variables

    private void updateJTable() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void UpdateJTable() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void If(boolean equals) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
