/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapplication;
import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.blue;
import static java.awt.Color.red;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import myapplication.userdetail;
import java.sql.*;
import javax.swing.*;
import static myapplication.loginSsystem.jComboBox1;
import static myapplication.userdetail.name1;
import static myapplication.userdetail.name2;

/**
 *
 * @author Vs
 */
public class studentLogIn extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
    /**
     * Creates new form studentLogIn
     */
    public studentLogIn() {
        initComponents();
        updateCombo();  
         this.setLocationRelativeTo(null);  //make the frame to center
    }
    public void updateCombo(){   // its for combox to fatch number of data data from the database 
  
    try{
   conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/adminlogin","root","root");
   String sql = " Select * from studentdetails ";
   pst = conn.prepareStatement(sql);
   rs = pst.executeQuery();
   while(rs.next())
   {
   String name = rs.getString("rollno");
   rollno.addItem(name);
      
   }
    }
    catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        checkbox = new javax.swing.JCheckBox();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        mini = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rollno = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(475, 371));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(730, 374));
        jPanel1.setMinimumSize(new java.awt.Dimension(730, 374));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 40)); // NOI18N
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 135, 70));

        checkbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkbox.setText("show password");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        jPanel1.add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, 30));

        password.setFont(new java.awt.Font("SimHei", 0, 18)); // NOI18N
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 310, 40));

        username.setFont(new java.awt.Font("SimHei", 0, 18)); // NOI18N
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 310, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("LogIn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 154, 45));

        exit.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        exit.setText("x");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 20, 30));

        mini.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        mini.setText("-");
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMouseExited(evt);
            }
        });
        jPanel1.add(mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 20, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javax/man.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javax/web(1).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 40));

        rollno.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        rollno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select_Roll_NO" }));
        jPanel1.add(rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 140, 40));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, -70, 790, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
      try{  
        conn = MySqlConnection.ConnectDB();
        
       String Sql="Select * from `adminlogin`.`studentdetails` where username='"+username.getText()+"' and pssword='"+password.getText()+"' and rollno='"+rollno.getSelectedItem().toString()+"'";
        //here select from table waale me table ka maan lekhte hai
        //database ek he hoota hai bs usme "`adminlogin`.`login`" ye waala sb ka alag hooota hai so that
        //ek databse ke ander he kethne saare "select * from <tablename>" add ho sake
        
        
        
        try{
          
        
        Statement st = conn.createStatement();
        
        ResultSet rs = st.executeQuery(Sql);
        
        if(rs.next())
        {
        new studentform2().setVisible(true);
        dispose();
        
          
          studentform2.stdno.setText(studentLogIn.rollno.getSelectedItem().toString());
          studentform2.studentname.setText(studentLogIn.username.getText());         
        
        
        }
        else
        {
        JOptionPane.showMessageDialog(null,"check your input data","access denied",JOptionPane.ERROR_MESSAGE);
        }
        }
        
        catch(SQLException e){
        
        JOptionPane.showMessageDialog(null,e);
        
        } 
        
        
      }
      catch(Exception e){
      JOptionPane.showMessageDialog(null,e);
      } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        if(checkbox.isSelected())
        {
        password.setEchoChar((char)0);        
        }
        else
            password.setEchoChar('*');
    }//GEN-LAST:event_checkboxActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
if(evt.getKeyCode() == KeyEvent.VK_ENTER)
      {
          conn = MySqlConnection.ConnectDB();
      
      String Sql="Select * from `adminlogin`.`studentdetails` where username=? and password=?";
             //here select from table waale me table ka maan lekhte hai 
             //database ek he hoota hai bs usme "`adminlogin`.`login`" ye waala sb ka alag hooota hai so that 
             //ek databse ke ander he kethne saare "select * from <tablename>" add ho sake 
      try{
        
    pst=conn.prepareStatement(Sql);
      pst.setString(1,username.getText());
      pst.setString(2,password.getText());      
      rs=pst.executeQuery();
      
      if(rs.next())
      {
          // JOptionPane.showMessageDialog(null,"welcone user");
        studentform2 w = new studentform2();
      w.setVisible(true); 
      dispose();
      }
      else
      {
      JOptionPane.showMessageDialog(null,"Invalid user-name or password","access denied",JOptionPane.ERROR_MESSAGE);
      }
      }
      catch(SQLException e){
      
          JOptionPane.showMessageDialog(null,e);
         
      }
      }
    }//GEN-LAST:event_passwordKeyPressed

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
 username.setText("");
   
      username.setForeground(black);          // TODO add your handling code here:
    }//GEN-LAST:event_usernameMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
  exit.setVisible(false);  
  dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
exit.setForeground(red);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
exit.setForeground(black);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseExited

    private void miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseEntered
mini.setForeground(blue);        // TODO add your handling code here:
    }//GEN-LAST:event_miniMouseEntered

    private void miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseExited
mini.setForeground(black);        // TODO add your handling code here:
    }//GEN-LAST:event_miniMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel mini;
    private javax.swing.JPasswordField password;
    public static javax.swing.JComboBox<String> rollno;
    public static javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
