/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapplication;

import static java.awt.Color.black;
import static java.awt.Color.gray;
import static java.awt.Color.red;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author manas singh
 */
public class studentCLassRoom extends javax.swing.JFrame {
Connection conn=null;            //these are local variable thus local variable are decleared there and global variables are decleared abouve i.e. import waale section me 
PreparedStatement pst=null;
ResultSet rs=null;
    /**
     * Creates new form studentCLassRoom
     */
    public studentCLassRoom() {
        initComponents();
        this.setLocationRelativeTo(null);
        Update_tables();
         Update_tables1(); 
        
    }
     private void Update_tables(){
     try {
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/adminlogin","root","root");
         String sql = "Select rollno , stdname from studentdetails";       // Select rollno , "stdname" from studentdetails  if we use these invented comosc then values inside these comoas are shown 
            pst = conn.prepareStatement(sql);
             rs = pst.executeQuery();
             table.setModel(DbUtils.resultSetToTableModel(rs));
    
     }
     catch (SQLException e) {
        JOptionPane.showMessageDialog(null,e);
     } 
 }
  private void Update_tables1(){
     try {
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/adminlogin","root","root");
         String sql = "Select username,subject from login";       // Select rollno , "stdname" from studentdetails  if we use these invented comosc then values inside these comoas are shown 
            pst = conn.prepareStatement(sql);
             rs = pst.executeQuery();
             table2.setModel(DbUtils.resultSetToTableModel(rs));
    
     }
     catch (SQLException e) {
        JOptionPane.showMessageDialog(null,e);
     } 
 }     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        mini = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        stdname = new javax.swing.JLabel();
        stdRollNO = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        defaultpanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        teacherpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        studentPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        get = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1046, 529));
        setMinimumSize(new java.awt.Dimension(1046, 529));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1046, 529));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javax/classroom.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javax/attnedance.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javax/result.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javax/timetable.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javax/assignmnets.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javax/notes.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 530));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLass-ROOM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 180, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javax/user.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 70, -1));

        exit.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, 30));

        mini.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        mini.setText("-");
        getContentPane().add(mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stdname.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        stdname.setText("******");
        jPanel3.add(stdname, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 64, -1, -1));

        stdRollNO.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        stdRollNO.setText("******");
        jPanel3.add(stdRollNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 94, -1, -1));

        mainpanel.setBackground(new java.awt.Color(51, 51, 51));
        mainpanel.setForeground(new java.awt.Color(51, 51, 51));
        mainpanel.setLayout(new java.awt.CardLayout());

        defaultpanel.setBackground(new java.awt.Color(102, 102, 102));
        defaultpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javax/imac-dashboard-crm-pie-chart-praph-cloud-512.png"))); // NOI18N
        defaultpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -60, -1, -1));

        mainpanel.add(defaultpanel, "card4");

        teacherpanel.setBackground(new java.awt.Color(102, 102, 102));
        teacherpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TeacherName", "Subject"
            }
        ));
        jScrollPane2.setViewportView(table2);

        teacherpanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 21, 380, 343));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javax/teacher.png"))); // NOI18N
        teacherpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javax/desk(1).png"))); // NOI18N
        teacherpanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, -1, -1));

        mainpanel.add(teacherpanel, "card3");

        studentPanel.setBackground(new java.awt.Color(102, 102, 102));
        studentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RollNo", "Student Name"
            }
        ));
        jScrollPane1.setViewportView(table);

        studentPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 380, 358));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\manas singh\\Downloads\\student.png")); // NOI18N
        studentPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 160, 180));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\manas singh\\Downloads\\students(2).png")); // NOI18N
        studentPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 190, 160));

        mainpanel.add(studentPanel, "card2");

        jPanel3.add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 940, 400));

        get.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Option", "Teacher", "Students" }));
        get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getActionPerformed(evt);
            }
        });
        jPanel3.add(get, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 170, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, -10, 970, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        studentform2 std = new studentform2();
      
      studentform2.studentname.setText(studentCLassRoom .stdname.getText());
      studentform2.stdno.setText(studentCLassRoom .stdRollNO.getText());
      
       std.setVisible(true);
       dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setForeground(red);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setForeground(black);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseExited

    private void getActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getActionPerformed
        if(get.getSelectedItem().toString().equals("Choose Option"))
 {
     JOptionPane.showMessageDialog(null,"invalid selection ","access denied",JOptionPane.ERROR_MESSAGE);
 }
 else if(get.getSelectedItem().toString().equals("Teacher"))
 {
   mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        // add panel
        mainpanel.add(teacherpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
        
 }
         else if(get.getSelectedItem().toString().equals("Students"))
 {
   mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        // add panel
        mainpanel.add(studentPanel);
        mainpanel.repaint();
        mainpanel.revalidate();
        
 }
    }//GEN-LAST:event_getActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
 studentTimeTAble std = new studentTimeTAble();
      
      studentTimeTAble.stdname.setText(studentCLassRoom .stdname.getText());
     studentTimeTAble.stdRollNO.setText(studentCLassRoom .stdRollNO.getText());
      
       std.setVisible(true);
       dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
 studentAttendance std = new studentAttendance();
      
     studentAttendance.stdname.setText(studentCLassRoom .stdname.getText());
    studentAttendance.wwww.setText(studentCLassRoom .stdRollNO.getText());
      
       std.setVisible(true);
       dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
     studentAssignments std = new studentAssignments();
      
     studentAssignments.stdname.setText(studentCLassRoom .stdname.getText());
   studentAssignments.stdRollNO.setText(studentCLassRoom .stdRollNO.getText());
      
       std.setVisible(true);
       dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
studentResult std = new studentResult();
      
  studentResult.stdname.setText(studentCLassRoom .stdname.getText());
  studentResult.stdRollNO.setText(studentCLassRoom .stdRollNO.getText());
      
       std.setVisible(true);
       dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
studentNotes std = new studentNotes();
      
  studentNotes.stdname.setText(studentCLassRoom .stdname.getText());
  studentNotes.stdRollNO.setText(studentCLassRoom .stdRollNO.getText());
      
       std.setVisible(true);
       dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentCLassRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentCLassRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentCLassRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentCLassRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentCLassRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel defaultpanel;
    public static javax.swing.JLabel exit;
    private javax.swing.JComboBox<String> get;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainpanel;
    public static javax.swing.JLabel mini;
    public static javax.swing.JLabel stdRollNO;
    public static javax.swing.JLabel stdname;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JTable table;
    private javax.swing.JTable table2;
    private javax.swing.JPanel teacherpanel;
    // End of variables declaration//GEN-END:variables
}
